from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class NotificationChannel(Protocol):
    @property
    def name(self) -> str: ...
    async def send(self, notification: dict) -> bool: ...
    async def health_check(self) -> bool: ...
    async def close(self) -> None: ...
